import { makeStyles } from "@mui/styles";

export default makeStyles({
  heroMain: {
    display: "flex",
    background: "#192841",
    height: "100vh",
    overflowY: "hidden",
  },
  pageContent: {
    padding: "20px",
  },
  heroRightMain: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    marginLeft: "275px",
    overflowX: "hidden",
    overflowY: "scroll",
  },
  heroRightTop: {
    display: 'flex',
    paddingTop: '40px',
    paddingLeft: '50px',
    paddingRight: '50px',
    flexDirection: 'column',
    paddingBottom: '40px'
  },
  cardMain: {
    display: "flex",
    width: "198.5px",
    height: "146px",
    padding: "16px",
    justifyContent: "space-between",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.30)",
    background: "rgba(0, 0, 0, 0.05)",
    backdropFilter: "blur(22px)",
  },
  logoAndTextWrap: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  cardTitle: {
    color: "#F9FAFB",
    textEdge: "cap",
    fontSize: "16px !important",
    fontWeight: "800 !important",
    lineHeight: "100%",
    marginBottom: "5px",
  },
  cardDescription: {
    color: "#FFF",
    fontSize: "16px !important",
    fontWeight: "275 !important",
    lineHeight: "100%",
  },
  heroCardContainer: {
    display: "flex",
    alignItems: "center",
    gap: "30px",
    marginTop: "100px",
  },
  addTitleCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    width: "198.5px",
    height: "146px",
    padding: "16px",
    borderRadius: "16px",
    border: "1px solid var(--bg-blur-storke, rgba(255, 255, 255, 0.30))",
    background: "rgba(0, 0, 0, 0.05)",
    backdropFilter: "blur(22px)",
  },
  smallCards: {
    display: "flex",
    height: "144px",
    padding: "24px",
    flexDirection: "column",
    justifyContent: "space-between",
    flex: "1 0 0",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.30)",
    background: "rgba(255, 255, 255, 0.10)",
  },
  smallCardtitleTypo: {
    color: "#FFF",
    fontSize: "20px !important",
    fontWeight: "300 !important",
    lineHeight: "100% !important",
  },
  smallCardDescTypo: {
    color: "#FFF",
    fontSize: "28px !important",
    fontWeight: "700 !important",
    lineHeight: "100% !important",
  },
  bigcardMain: {
    display: "flex",
    width: "409px",
    height: "455px",
    padding: "24px",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.30)",
    background: "rgba(255, 255, 255, 0.10)",
  },
  bigcardheading: {
    color: "#FFF",
    fontSize: "20px !important",
    fontWeight: "800 !important",
    lineHeight: "100% !important ",
  },
  seeAll: {
    color: "#FFF",
    fontSize: "14px !important",
    fontWeight: "700 !important",
    lineHeight: "100% !important",
    cursor: "pointer",
  },
  flexCSpBet: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "-webkit-fill-available",
  },
  bigCardDesc: {
    color: "#FFF",
    fontSize: "14px !important",
    fontWeight: "300 !important",
    lineHeight: "100%",
  },
  pgTypo: {
    color: "#FFF",
    fontSize: "14px !important",
    fontWeight: "400 !important",
    lineHeight: "100%",
  },

  cretNew: {
    display: "flex !important",
    padding: "16px !important",
    justifyContent: "center !important",
    alignItems: "center !important",
    gap: "8px !important",
    alignSelf: "stretch !important",
    borderRadius: "8px !important",
    border: "1px solid #E5E7EB !important",
    background: "rgba(255, 255, 255) !important",
    width: "100% !important",
  },
  projectListWrap: {
    display: "flex",
    flexDirection: "column",
    gap: "39px",
  },
  singleListBox: {
    paddingBottom: "20px",
    borderBottom: "1px solid rgb(229, 231, 235)",
    display: "flex",
    gap: "14px",
  },
  newJoinerListBox: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    width: "100%",
  },
  newJoinerListWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  offerMainBox: {
    display: "flex",
    width: "75%",
    padding: "24px",
    flexDirection: "column",
    gap: "8px",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.30)",
    background: "rgba(255, 255, 255, 0.10)",
  },
  offerHeading: {
    color: "#FFF",
    fontSize: "32px !important",
    fontWeight: "800 !important",
  },
  bottomLeftWrapper: {
    gap: "25px",
    display: "flex",
    flexDirection: "column",
    height: "-webkit-fill-available",
    width: "65%",
  },
  bottomRightWrapper: {
    gap: "25px",
    display: "flex",
    flexDirection: "column",
    height: "-webkit-fill-available",
    width: "30%",
  },
  cardPacket: {
    display: "flex",
    alignItems: "center",
    gap: "25px",
  },
  FeedMain: {
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.30)",
    background: "rgba(255, 255, 255, 0.10)",
    padding: "24px",
  },
  postMain: {
    display: "flex",
    padding: "17px 18px",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "24px",
    borderRadius: "8px",
    background: "#192841",
    height: "100%",
  },
});
